[config]
schema = "1.0.0"
url = "https://raw.githubusercontent.com/Wrench56/A-PluginTemplate/main/Plugin.toml"

[plugin]
name = "A-PluginTemplate"
version = "0.0.1"
zip_url = "https://github.com/Wrench56/A-PluginTemplate/archive/refs/heads/main.zip"

[dependencies]
[dependencies.python]
version = "^3.7.0"
requirements_file = "./requirements.txt"
